import { useState } from "react";
import { ListPageTemplate } from "@/components/templates/list-page";
import type { Column } from "@/components/ds/data-table";
import { useManagerEvents } from "../hooks/manager.api";
import { ApiEvent } from "@/modules/events/services/events.api";
import { EventDetailsDialog } from "@/components/events/EventDetailsDialog";

export function ManagerRevenuePage() {
  const { data: events = [], isLoading } = useManagerEvents();
  const [selectedDetailEvent, setSelectedDetailEvent] = useState<ApiEvent | null>(null);

  const columns: Column<ApiEvent>[] = [
    {
      key: "name",
      header: "Event",
      sortable: true,
      render: (row) => (
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation();
            setSelectedDetailEvent(row);
          }}
          className="font-medium text-primary hover:underline text-left"
        >
          {row.name}
        </button>
      ),
    },
    {
      key: "revenue",
      header: "Revenue",
      render: (row) => (
        <span className="font-medium text-emerald-600 dark:text-emerald-400">
          ₹{(row.revenue || 0).toLocaleString("en-IN")}
        </span>
      ),
    },
  ];

  return (
    <>
      <ListPageTemplate<ApiEvent>
        title="Event Revenue"
        description="View revenue generated by your events."
        crumbs={[{ label: "Manager" }, { label: "Event Revenue" }]}
        columns={columns}
        rows={events}
        loading={isLoading}
        searchKeys={["name"]}
        selectable={false}
      />

      <EventDetailsDialog
        open={!!selectedDetailEvent}
        onOpenChange={(open) => !open && setSelectedDetailEvent(null)}
        event={selectedDetailEvent}
        mode="manager"
      />
    </>
  );
}
